### ISSUE TITLE
Error while applying Vanguard on the reentrant1.sol provided example

### ISSUE THREAD

**Issue by acmLL** [Veridise/Vanguard#95]
Hi,

   I created a docker image using the description. I had to adapt some parts due to errors but at the end, I got an image. But when I run: python3 run.py --src_path=solidity_benchmarks/examples/reentrancy/reentrant1.sol --detector=reentrancy

I got this error message

----Preprocessing solidity_benchmarks/examples/reentrancy/reentrant1.sol----
Running Solidity summarizer...Completed Solidity summarizer, summary at /vanguard/processed_examples/reentrant1_summary.json.
Running Solidity preprocessor...Completed Solidity preprocessor, preprocessed version at /vanguard/processed_examples/reentrant1_instrumented.sol.
Running Solang...Traceback (most recent call last):
  File "/vanguard/run.py", line 226, in <module>
    run(args)
  File "/vanguard/run.py", line 208, in run
    summary_path = preprocess_file(args, lang, ext)
  File "/vanguard/run.py", line 96, in preprocess_file
    subprocess.check_output(solang_cmd.split(), stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['solang', '--target', 'ewasm', '--emit', 'llvm-bc', '-o', '/vanguard/processed_examples', '/vanguard/processed_examples/reentrant1_instrumented.sol']' returned non-zero exit status 255.

What could be? Thanks!

**Comment by stephensj2** [comment]
It seems like there was an error compiling the contract with Solang for some reason. We had issues with Solang's stability, which is part of the reason why we've been building our new version of Vanguard that uses our own LLVM frontend (for example, in some of our tests block comments in certain locations caused compilation errors). I'm not sure why Solang is having compilation issues with this particular contract though since it did compile in the past.

This version of vanguard was meant for demo purposes only because of the Solang stability problems. We have since been working on a new version of Vanguard that is currently in beta and is in the V1 branch. This version of Vanguard is still under active development but should be more stable than what is in main. We plan to merge V1 into main soon.

**Comment by acmLL** [comment]
Thanks, @stephensj2 ! I tried to install the version in the V1 branch and opened an issue in another thread...
